[project]
name = "NFE_Alert"
version = "0.1.0"
description = "Revisión de domicilios fiscales electronicos de Argentina"
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "alembic==1.15.2",
    "beautifulsoup4==4.13.4",
    "bs4==0.0.2",
    "certifi==2025.4.26",
    "chardet==5.2.0",
    "charset-normalizer==3.4.2",
    "click==8.2.0",
    "colorama==0.4.6",
    "contourpy==1.3.2",
    "cssselect==1.3.0",
    "cycler==0.12.1",
    "datarecorder==3.6.2",
    "dotenv==0.9.9",
    "downloadkit==2.0.7",
    "drissionpage==4.0.5.6",
    "et-xmlfile==2.0.0",
    "filelock==3.18.0",
    "fonttools==4.57.0",
    "geopandas==1.0.1",
    "greenlet==3.2.2",
    "idna==3.10",
    "kiwisolver==1.4.8",
    "logger==1.4",
    "lxml==5.4.0",
    "mako==1.3.10",
    "markupsafe==3.0.2",
    "matplotlib==3.10.3",
    "numpy==2.2.5",
    "openpyxl==3.1.5",
    "packaging==25.0",
    "pandas==2.2.3",
    "pillow==11.2.1",
    "playwright==1.52.0",
    "playwright-stealth==1.0.6",
    "psutil==7.0.0",
    "pyee==13.0.0",
    "pyminizip==0.2.6",
    "pyodbc==5.2.0",
    "pyogrio==0.11.0",
    "pyparsing==3.2.3",
    "pyproj==3.7.1",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.0",
    "pytz==2025.2",
    "pywin32==310",
    "reportlab==4.4.0",
    "requests==2.32.3",
    "requests-file==2.1.0",
    "setuptools==80.4.0",
    "shapely==2.1.0",
    "six==1.17.0",
    "soupsieve==2.7",
    "sqlalchemy==2.0.40",
    "tldextract==5.3.0",
    "typing-extensions==4.13.2",
    "tzdata==2025.2",
    "urllib3==2.4.0",
    "uv==0.7.3",
    "websocket-client==1.8.0",
    "winshell==0.6",
]
