[pytest]
minversion = 6.0
addopts = -ra -q -x --durations=5
; testpaths =
;     tests
markers =
    base: marca los test de coherencia en los resultados
    error: marca los test que verifican que no haya errores

; Los addopts en tu archivo pytest.ini son:

; -ra: Muestra un resumen de todos los resultados de las pruebas al final de la ejecución de las pruebas.
; -q: Ejecuta las pruebas en modo silencioso.
; -x: Detiene la ejecución de las pruebas después del primer fallo.
; Algunos de los addopts más comunes en pytest son:

; -v o --verbose: Aumenta la verbosidad.
; --cov: Utilizado con el plugin pytest-cov para medir la cobertura del código.
; --html: Utilizado con el plugin pytest-html para generar un informe de las pruebas en formato HTML.
; -s: Desactiva la captura de salida, permitiendo imprimir directamente en la consola.
; --durations: Muestra los tiempos de ejecución de las pruebas más lentas.
; -k: Permite ejecutar pruebas específicas basadas en su nombre.