"""crear_tablas_iniciales

Revision ID: 42ffb5e7d983
Revises: 
Create Date: 2025-04-23 17:00:05.337704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ffb5e7d983'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procesamientos_diarios_global',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('numero_procesamiento', sa.Integer(), nullable=False),
    sa.Column('iniciado', sa.DateTime(), nullable=False),
    sa.Column('finalizado', sa.DateTime(), nullable=True),
    sa.Column('procesamiento_correcto', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procesamientos_diarios_global_id'), 'procesamientos_diarios_global', ['id'], unique=False)
    op.create_table('monitoreo_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('iniciado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('id_procesamiento_diario_global', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_procesamiento_diario_global'], ['procesamientos_diarios_global.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoreo_bots_id'), 'monitoreo_bots', ['id'], unique=False)
    op.create_index(op.f('ix_cliente_jurisdiccion_id'), 'cliente_jurisdiccion', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_jurisdicciones_id'), 'jurisdicciones', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_cliente_id'), 'usuario_cliente', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_autorizados_id'), 'usuarios_autorizados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_autorizados_id'), table_name='usuarios_autorizados')
    op.drop_index(op.f('ix_usuario_cliente_id'), table_name='usuario_cliente')
    op.drop_index(op.f('ix_jurisdicciones_id'), table_name='jurisdicciones')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_cliente_jurisdiccion_id'), table_name='cliente_jurisdiccion')
    op.drop_index(op.f('ix_monitoreo_bots_id'), table_name='monitoreo_bots')
    op.drop_table('monitoreo_bots')
    op.drop_index(op.f('ix_procesamientos_diarios_global_id'), table_name='procesamientos_diarios_global')
    op.drop_table('procesamientos_diarios_global')
    # ### end Alembic commands ###
