"""Add proceso column to monitoreo_bots

Revision ID: c36cefc2418a
Revises: 42ffb5e7d983
Create Date: 2025-04-28 15:43:33.689392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36cefc2418a'
down_revision: Union[str, None] = '42ffb5e7d983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoreo_bots', sa.Column('proceso', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoreo_bots', 'proceso')
    # ### end Alembic commands ###
