-- APAGAR JURISDICCIONES
-- actualizar consultar a 0 para apagar determinadas jurisdicciones de determinados cliente
BEGIN TRANSACTION;
UPDATE [nfe_alert].[dbo].[cliente_jurisdiccion]
SET consultar = 0
WHERE cliente_id = 32 AND jurisdiccion_id = 3;
-- COMMIT TRANSACTION;
ROLLBACK TRANSACTION;

SELECT *
FROM [nfe_alert].[dbo].[cliente_jurisdiccion]
WHERE cliente_id = 32 AND jurisdiccion_id = 3;



-- APAGAR CLIENTE
-- actualizar documentacion a 0 para apagar determinados clientes
BEGIN TRANSACTION;

UPDATE [nfe_alert].[dbo].[clientes]
SET documentacion = 0
WHERE id in (8, 13, 14, 25, 27);
-- COMMIT TRANSACTION;
ROLLBACK TRANSACTION;

SELECT *
FROM [nfe_alert].[dbo].[clientes]
where id in (8, 13, 14, 25, 27);


-- JURISDICCIONES
-- 2	Nacional
-- 3	SICNEA
-- 4	901 CABA
-- 5	902 BUENOS AIRES
-- 6	903 CATAMARCA
-- 7	904 CORDOBA
-- 8	905 CORRIENTES
-- 9	906 CHACO
-- 10	907 CHUBUT
-- 11	908 ENTRE RIOS
-- 12	909 FORMOSA
-- 13	910 JUJUY
-- 14	911 LA PAMPA
-- 15	912 LA RIOJA
-- 16	913 MENDOZA
-- 17	914 MISIONES
-- 18	915 NEUQUEN
-- 19	916 RIO NEGRO
-- 20	917 SALTA
-- 21	918 SAN JUAN
-- 22	919 SAN LUIS
-- 23	920 SANTA CRUZ
-- 24	921 SANTA FE
-- 25	922 SANTIAGO DEL ESTERO
-- 26	923 TIERRA DEL FUEGO
-- 27	924 TUCUMAN

-- CLIENTES
-- 3	ABBVIE S.A
-- 4	ADIDAS ARGENTINA S.A - ARCA
-- 5	ADIDAS ARGENTINA S.A - PROVINCIALES
-- 6	BIOGEN ARGENTINA S.R.L
-- 7	BIOMARIN ARGENTINA S.R.L
-- 8	COMPANIA DE INVERSIONES DE ENERGIA S.A
-- 9	CYANAMID DE ARGENTINA S A SUC BS AS
-- 10	EDGE ARGENTINA S.R.L
-- 11	EUROP ASSISTANCE ARGENTINA S.A
-- 12	FACEBOOK ARGENTINA S.R.L
-- 13	FUNDACION TGS
-- 14	GAS LINK S.A
-- 15	J&J ARGENTINA S.A
-- 16	JANSSEN CILAG FARMACEUTICA S.A
-- 17	JOHNSON & JOHNSON MEDICAL S.A
-- 18	MAGNETI MARELLI CONJ.DE ESCAPE S.A
-- 19	MAGNETI MARELLI REPUESTOS S.A
-- 20	PFIZER S.R.L - ARCA
-- 21	PFIZER S.R.L - PROVINCIALES
-- 22	PFIZER S.R.L - SICNEA
-- 23	SIMPLOT ARGENTINA S.R.L
-- 24	SPOTIFY ARGENTINA S.A
-- 25	TELCOSUR S.A
-- 26	THE BRITISH COUNCIL
-- 27	TRANSPORTADORA DE GAS DEL SUR S.A
-- 28	ULTRAGENYX ARGENTINA S.R.L
-- 29	VERIZON ARGENTINA S.R.L

