-- SQLite
UPDATE clientes SET pass = 'Dttadidas2025.' WHERE nombre IN ('ADIDAS ARGENTINA S.A - PROVINCIALES', 'ADIDAS ARGENTINA S.A - ARCA');

SELECT *
FROM clientes
WHERE nombre IN ('ADIDAS ARGENTINA S.A - PROVINCIALES', 'ADIDAS ARGENTINA S.A - ARCA');